create database galazery;

create table projects(
  project_id int generated by default as identity primary key,
  project_name varchar(100) not null,
  project_photo varchar(70) not null,
  project_link varchar(100) not null
);

create table services (
  service_id int generated by default as identity primary key,
  service_name varchar(200)
);

create table orders(
  order_id int generated by default as identity primary key,
  order_about text not null,
  tel varchar(32) not null,
  service_id int not null references services(service_id),
  created_at timestamp with time zone default current_timestamp
);

create table users(
  user_id int generated by default as identity primary key,
  username varchar(32) not null,
  password varchar(64) not null,
  role smallint default 0
);

create extension pgcrypto;

create unique index username_idx on users (lower(username));

